### ISSUE TITLE
Feb 18 13:44:55 webshs001 SHIPS/2.0[44512]: xxxxx (IdentDevice) @ webshs001 - device could not be validated @ /opt/SHIPS-master/lib/servlets/password.rb:73:in `login'

### ISSUE THREAD

**Issue by tnassersisteer** [trustedsec/SHIPS#17]
When I try to update passwd for a client :

./ships.sh server says unable to process request

Log from a server Ships 
Feb 18 13:44:55 webshs001 SHIPS/2.0[44512]: xxxxx (IdentDevice) @ webshs001 - device could not be validated @ /opt/SHIPS-master/lib/servlets/password.rb:73:in `login'

Any idea please

**Comment by GeoffWalton** [comment]
Depends on the configuration.  Most likely the nonce value is out of sync between the device and the server. Simplest fix is probably just delete the device on the server side.

[https://www.trustedsec.com/wp-content/uploads/2018/10/TS_Wordmark_grn-e1539701369375-1.png]<http://trustedsec.com/>
Geoff Walton
Senior Security Consultant
o:
877.550.4728  m:440.344.8967
[cid:image002.png@01D46545.2E19F970]<https://twitter.com/TrustedSec> [cid:image003.png@01D46545.2E19F970] <https://www.facebook.com/1trustedsec/>  [cid:image004.png@01D46545.2E19F970] <https://www.linkedin.com/company/trustedsec-llc/>

**Comment by tnassersisteer** [comment]
Dear Geoff Walton.
This is the solution that was applied, it works for some machines, unfortunately not for the whole
BR
Tarik

**Comment by GeoffWalton** [comment]
Any pattern to the machines that are failing? That is where I’d have to start. You can possibly see the nonce that is being send in the request log as well. Should the case be the client isn’t writing the local file.

[https://www.trustedsec.com/wp-content/uploads/2018/10/TS_Wordmark_grn-e1539701369375-1.png]<http://trustedsec.com/>
Geoff Walton
Senior Security Consultant
o:
877.550.4728  m:440.344.8967
[cid:image002.png@01D46545.2E19F970]<https://twitter.com/TrustedSec> [cid:image003.png@01D46545.2E19F970] <https://www.facebook.com/1trustedsec/>  [cid:image004.png@01D46545.2E19F970] <https://www.linkedin.com/company/trustedsec-llc/>

**Comment by tnassersisteer** [comment]
Dear Geoff Walton.

Thanks for your help.

**Any pattern to the machines that are failing :** No is random.

Log from a server Ships : 

Apr  8 15:35:29 XXXXX SHIPS/2.0[87117]: accept: XXXXX:28951
Apr  8 15:35:29 XXXXX SHIPS/2.0[87117]: ServletPassword is invoked.
Apr  8 15:37:36 XXXXX SHIPS/2.0[87117]: XXXXX  (IdentDevice) @ XXXXX - device could not be validated @ /opt/SHIPS-master/lib/servlets/password.rb:73:in `login'
Apr  8 15:37:36 XXXXX SHIPS/2.0[87117]: close: XXXXX:28951
Apr  8 15:37:37 XXXXX rsyslogd-pstats: global: origin=dynstats

Have you any idea ?

Best Regards.
Tarik
