### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by hallzi** [trustedsec/SHIPS#8]
Hi

I'm having some problems running on Windows, what are your recommendations to run it on Windows 2012 R2 ?

I'm getting errors like
c:/Ruby21-x64/lib/ruby/2.1.0/webrick/server.rb:47:in `setsid': setsid() function is unimplemented on this machine (NotImplementedError)
        from c:/Ruby21-x64/lib/ruby/2.1.0/webrick/server.rb:47:in `start'
        from c:/admin/SHIPS/SHIPS-master/SHIPS.rb:37:in `<main>'

**Comment by GeoffWalton** [comment]
Try setting foreground to try in the app: section of the config.  The process is attempting to become a daemon, which will not be possible on Windows.

Geoff Walton | Senior Security Consultant
CISSP
TRUSTEDSEC, LLC
Cell: 440.344.8967 | US EDT (GMT -5)
Staunton, VA Office
Email: geoff.walton@trustedsec.com<mailto:geoff.walton@trustedsec.com>
https://www.trustedsec.com<https://www.trustedsec.com/>

"INFORMATION SECURITY MADE SIMPLE" - TRUSTEDSEC

**Comment by hallzi** [comment]
Thanks for that, now I run into another issue.
Seems like it's trying to use a function not supported by Windows.

c:/Ruby21-x64/lib/ruby/2.1.0/webrick/server.rb:46:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from c:/Ruby21-x64/lib/ruby/2.1.0/webrick/server.rb:46:in `start'
        from c:/admin/SHIPS/SHIPS-master/SHIPS.rb:37:in `<main>'
